// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Problem struct {
	ID              uuid.UUID
	Title           string
	Difficulty      string
	DescriptionPath string
	TestcasesPath   string
	Tags            []string
	TimeLimit       float64
	MemoryLimit     float64
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Submission struct {
	ID         uuid.UUID
	ProblemID  uuid.UUID
	UserID     uuid.UUID
	Language   int32
	SourceCode string
	Status     string
	UpdatedAt  time.Time
	CreatedAt  time.Time
}

type SubmissionResult struct {
	ID             uuid.UUID
	SubmissionID   uuid.UUID
	JudgeToken     string
	Stdin          string
	Stdout         string
	ExpectedOutput string
	StatusID       int32
	TimeUsed       string
	MemoryUsed     float64
	JudgeResponse  []byte
	UpdatedAt      time.Time
	CreatedAt      time.Time
}

type User struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Password  string
	CreatedAt time.Time
}
