// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: problems.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createProblem = `-- name: CreateProblem :one
INSERT INTO problems (
    id,
    title,
    difficulty,
    description_path,
    testcases_path,
    tags,
    time_limit,
    memory_limit
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
) RETURNING id, title, difficulty, description_path, testcases_path, tags, time_limit, memory_limit, created_at, updated_at
`

type CreateProblemParams struct {
	ID              uuid.UUID
	Title           string
	Difficulty      string
	DescriptionPath string
	TestcasesPath   string
	Tags            []string
	TimeLimit       float64
	MemoryLimit     float64
}

func (q *Queries) CreateProblem(ctx context.Context, arg CreateProblemParams) (Problem, error) {
	row := q.db.QueryRowContext(ctx, createProblem,
		arg.ID,
		arg.Title,
		arg.Difficulty,
		arg.DescriptionPath,
		arg.TestcasesPath,
		pq.Array(arg.Tags),
		arg.TimeLimit,
		arg.MemoryLimit,
	)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Difficulty,
		&i.DescriptionPath,
		&i.TestcasesPath,
		pq.Array(&i.Tags),
		&i.TimeLimit,
		&i.MemoryLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProblemByID = `-- name: GetProblemByID :one
SELECT id, title, difficulty, description_path, testcases_path, tags, time_limit, memory_limit, created_at, updated_at FROM problems WHERE id = $1
`

func (q *Queries) GetProblemByID(ctx context.Context, id uuid.UUID) (Problem, error) {
	row := q.db.QueryRowContext(ctx, getProblemByID, id)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Difficulty,
		&i.DescriptionPath,
		&i.TestcasesPath,
		pq.Array(&i.Tags),
		&i.TimeLimit,
		&i.MemoryLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProblems = `-- name: GetProblems :many
SELECT id, title, difficulty, description_path, testcases_path, tags, time_limit, memory_limit, created_at, updated_at FROM problems OFFSET $1 LIMIT $2
`

type GetProblemsParams struct {
	Offset int32
	Limit  int32
}

func (q *Queries) GetProblems(ctx context.Context, arg GetProblemsParams) ([]Problem, error) {
	rows, err := q.db.QueryContext(ctx, getProblems, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Problem
	for rows.Next() {
		var i Problem
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Difficulty,
			&i.DescriptionPath,
			&i.TestcasesPath,
			pq.Array(&i.Tags),
			&i.TimeLimit,
			&i.MemoryLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
